app/military_site/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings



urlpatterns = [
    path('', include('reports.urls', namespace='reports')),
    path('admin/', admin.site.urls),
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         path('__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

app/reports/urls.py
from django.urls import path, re_path
from django.views.generic import TemplateView

from . import views

app_name = "reports"

urlpatterns = [

    path('', views.index_view, name='index'),

    re_path(r'^reports_list/$', views.reports_list_view, name='reports_list'),
    path('proceed_chosen_report/<int:report_id>', views.proceed_chosen_report_view, name='proceed_chosen_report'),
    path('serviceman_list', views.serviceman_list_view, name='users'),

    re_path(r'^edit_chain/$', views.edit_service_members_chain_view, name='edit_service_members_chain'),
    re_path(r'^edit_chain/(?P<serviceman_id>\d+)$', views.edit_service_members_chain_view,
            name='edit_service_members_chain'),

    path('report_filling', views.report_filling_view, name='report_filling'),
    path('final_report', views.return_report_document_view, name='final_report'),

    re_path(r'^search_member/$', views.member_search_view),
    re_path(r'^search_member/(?P<name_format>[-\w]+)$', views.member_search_view),

    path('help/', TemplateView.as_view(template_name="reports/help.html"), name='help')

]

app/reports/forms.py
from django import forms


class ReportFillingForm(forms.Form):
    pass

app/reports/views.py
from django.shortcuts import render, redirect, reverse
from django.http import Http404
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import FileResponse
from django.http import HttpResponse

import json
import os
import datetime

from .models import Serviceman
from .models import Report

from . import main_report_controller as report_controller
from . import report_content_util
from . import report_forms_util


# Create your views here.
def index_view(request):
    """show few report generation option for user (basic report or custom_template)"""
    if request.user.is_authenticated:
        return redirect(reverse('reports:reports_list'))

    return render(request, 'reports/index.html')


@login_required
def reports_list_view(request):
    """show all reports"""
    if request.method == 'POST':
        filter_param = request.POST.get('filter_param')
        if (filter_param is not None) and (len(filter_param) > 0):
            cap_filter_param = filter_param.capitalize()
            reports_list = Report.objects.filter(
                Q(title__icontains=cap_filter_param) | Q(body_sample__icontains=cap_filter_param)
                |
                Q(title__icontains=filter_param) | Q(body_sample__icontains=filter_param)
            ).order_by('id')
        else:
            filter_param = ""
            reports_list = Report.objects.all().order_by('id')

        paginator = Paginator(reports_list, 5)
        page_obj = paginator.get_page(1)
        context = {
            'page_obj': page_obj,
            'filter_param': filter_param
        }

    elif request.method == 'GET':
        filter_param = request.GET.get('filter_param')
        if (filter_param is not None) and (len(filter_param) > 0):
            cap_filter_param = filter_param.capitalize()
            reports_list = Report.objects.filter(
                Q(title__icontains=cap_filter_param) | Q(body_sample__icontains=cap_filter_param)
                |
                Q(title__icontains=filter_param) | Q(body_sample__icontains=filter_param)
            ).order_by('id')
        else:
            filter_param = ""
            reports_list = Report.objects.all().order_by('id')

        paginator = Paginator(reports_list, 5)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context = {
            'page_obj': page_obj,
            'filter_param': filter_param
        }

    return render(request, 'reports/reports_list.html', context)


@login_required
def proceed_chosen_report_view(request, report_id):
    """
    proceed choosed report and define next step (show report filling form or users list to set up report owner )
    """
    request.session['report_id'] = report_id
    request.session.modified = True

    report = Report.objects.get(id=report_id)
    if report.type == 'regular':
        return redirect(reverse('reports:users'))
    elif report.type == 'custom':
        return redirect(reverse('reports:edit_service_members_chain'))


@login_required
def serviceman_list_view(request):
    """test view for showing users list. For choosing who generate report for"""
    serviceman_list = Serviceman.objects.all().order_by('id')
    paginator = Paginator(serviceman_list, 7)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'serviceman_list': page_obj
    }
    return render(request, 'reports/serviceman_list.html', context)


@login_required
def edit_service_members_chain_view(request, serviceman_id=None):
    """change servicemen chain if needed.
    automatically change member position and make him temporary boss on this position"""

    if request.method == 'POST':
        try:
            serviceman_chain = request.session['serviceman_chain']
            
            if 'edit_chain_id' in request.POST:
                swap_id = int(request.POST.get('edit_chain_id'))         

            elif 'submit_new_id' in request.POST:
                old_id = request.POST.get('submit_new_id')
                swap_id = request.POST.get('swap_id')
                if (swap_id is not None) and (old_id != swap_id):
                    for member in serviceman_chain:
                        if member.id == int(old_id):
                            replace_index = serviceman_chain.index(member)

                    new_serviceman = Serviceman.objects.get(id=int(swap_id))

                    initial_member_position = request.session['initial_serviceman_chain'][replace_index].position
                    # change position to temporary and unit
                    if new_serviceman.position != initial_member_position:
                        initial_member_position.temp_supervisor = True
                        initial_member_unit = request.session['initial_serviceman_chain'][replace_index].unit

                        # replace member in chain
                        new_serviceman.position = initial_member_position
                        new_serviceman.unit = initial_member_unit
                    serviceman_chain[replace_index] = new_serviceman

                    request.session['serviceman_chain'] = serviceman_chain
                    request.session.modified = True
                   
                    # change swap_id for proper template rendering (show 'next' button after editing)
                    swap_id = None

            elif 'remove_chain_id' in request.POST:
                remove_id = request.POST.get('remove_chain_id')
                for member in serviceman_chain:
                    if member.id == int(remove_id):
                        serviceman_chain.remove(member)
                request.session['serviceman_chain'] = serviceman_chain
                request.session.modified = True
                swap_id = None

            elif 'submit_chain_editing' in request.POST:
                return redirect(reverse('reports:report_filling'))
        except Exception as e:
            print(e)
            return redirect(reverse('reports:edit_service_members_chain', kwargs={'report_id': request.session['report_id']}))
        else:
            request.session['chain_modified'] = True
            serviceman_chain = request.session['serviceman_chain']

    #* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
    #* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
    elif request.method == 'GET':
        swap_id = None
        report_id = request.session['report_id']

        
        # custom report template case (report with no serviceman_id)
        if serviceman_id is None:
            try:
                serviceman_chain = report_content_util.get_servicemen_chain_list(report_id)
                request.session['serviceman_chain'] = serviceman_chain
                request.session['initial_serviceman_chain'] = serviceman_chain
            except Exception as e:
                print(e)
                raise Http404("Report template settings is incorrect")
        # regula report with serviceman_id specifyed
        else:
            #handling chain permanent state modification is user_id changed
            if 'serviceman_id' in request.session.keys() and serviceman_id != request.session['serviceman_id']:
                request.session['serviceman_id'] = serviceman_id
                del request.session['chain_modified']
            else:
                request.session['serviceman_id'] = serviceman_id

            # new variable for controlling chain modification (POST --> automatically return GET vith prepopulated data)
            try:
                if request.session['chain_modified'] is True:
                    serviceman_chain = request.session['serviceman_chain']
            except KeyError:
                #init service_men chain first time
                serviceman = Serviceman.objects.get(id=serviceman_id)
                serviceman_chain = report_content_util.get_servicemen_chain_list(report_id, serviceman)
                
                request.session['serviceman_chain'] = serviceman_chain
                request.session['initial_serviceman_chain'] = serviceman_chain
        request.session.modified = True


    context = {
        'serviceman_chain': serviceman_chain,
        'swap_id': swap_id,
    }
    return render(request, 'reports/edit_service_members_chain.html', context)


@login_required
def report_filling_view(request):
    """report filling form view"""
    if request.method == 'POST':
        document_file_path = report_controller.generate_report(request)
        request.session['report_file_path'] = document_file_path
        request.session.modified = True
        return redirect(reverse('reports:final_report'))

    report_id = request.session['report_id']
    context = report_forms_util.get_report_body_filling_form(report_id)
    return render(request, 'reports/report_filling.html', context)


@login_required
def return_report_document_view(request):
    """
    generate final document report
    :return: report docx file
    """

    document_file_path = request.session['report_file_path']
    response = FileResponse(open(document_file_path, 'rb'), as_attachment=True,
                            filename=document_file_path.split('\\')[-1])

    now = datetime.datetime.now()

    download_report_file_name = "" + now.strftime("%d-%m %H-%M") + " report" + "." + document_file_path.rsplit(".", 1)[-1]

    response['Content-Type'] = 'application/octet-stream'
    response['Content-Disposition'] = 'attachment;filename="{0}"'.format(download_report_file_name);
    response['Content-Length'] = os.path.getsize(document_file_path)
    return response


@login_required
def member_search_view(request):
    """
    Search for servicemember and return objects json array:
    :param request:

app/reports/templates/reports/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Reports</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

    <link rel="stylesheet" href="{% static 'fontawesome-free-5.11.2-web/css/all.css' %}">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" crossorigin="anonymous"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" rel="stylesheet"/>

    <script src="https://code.jquery.com/jquery-3.2.1.min.js" crossorigin="anonymous"
            integrity="sha384-xBuQ/xzmlsLoJpyjoggmTEz8OWUFM0/RC5BsqQBDX2v5cMvDHcMakNTNrHIW2I5f"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" crossorigin="anonymous"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" crossorigin="anonymous"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"></script>


    {#    import local bootstrap#}
{#    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-4.0.0/dist/css/bootstrap.css' %}"/>#}

    {#    custom css#}
    <link rel="stylesheet" type="text/css" href="{% static 'custom-css/custom_styles.css' %}"/>


    {% block extra_head %}
        {{ form.media }}
    {% endblock %}


</head>
<body>

{#<nav id="opacity-3" class="fixed-top navbar-expand navbar-dark bg-secondary opacity-0 left-bordered-row">#}
<nav class="fixed-top navbar-expand bg-secondary opacity-5">
    <div class="container form-inline">

        <a href="/" class="navbar-brand ml-3">
            <i class="fas fa-greater-than fa-2x text-light"></i></a>

            <div class="collapse navbar-collapse">
                {% if user.is_authenticated %}
                    <ul class="navbar-nav mr-auto d-flex align-items-center">
                        <li class="nav-item">
                            <a id="nav-bar-link-no-underline" href="{% url 'reports:index' %}">
                                <span class="nav-link text-light text-uppercase font-weight-normal px-3">
                                    <i class="fas fa-file-alt fa-2x text-danger"></i>
                                    <i class="fas fa-file-alt fa-2x text-warning"></i>
                                    <i class="fas fa-file-alt fa-2x text-light"></i>
                                </span>
                            </a>
                        </li>
                        {% if user.username == "admin" %}
                        <li class="nav-item"><a class="nav-link text-warning text-uppercase font-weight-bold px-3"
                                                href={% url 'reports:help' %}>СПИСОК шаблонных ПОЛЕЙ</a></li>
                        {% endif %}
                    </ul>

                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle align-self-baseline opacity-5" type="button"
                                id="dropdownMenuButton"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {# icon for loged in user #}
                             <span class="fas fa-user-circle fa-1x mr-2"></span><span>{{ user.username|upper }}</span>
                        </button>
                        <div class="dropdown-menu opacity-5" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="{% url 'logout' %}?next=/">Вийти<i
                                    class="fas fa-sign-out-alt ml-1"></i></a>
                        </div>
                    </div>



                {# not authenticated users#}
                {% else %}
                    <ul class="navbar-nav mr-auto">
                        <a id="nav-bar-link-no-underline" href="{% url 'reports:index' %}">
                                <span class="nav-link text-light text-uppercase font-weight-normal px-3">
                                    <i class="fas fa-file-alt fa-2x text-danger"></i>
                                    <i class="fas fa-file-alt fa-2x text-warning"></i>
                                    <i class="fas fa-file-alt fa-2x text-light"></i>
                                </span>
                            </a>
                    </ul>

                    {# login button #}
                    <div class="ml-auto">
                        {# login button#}
                        <a class="btn btn-outline-warning mr-2" href="{% url 'login' %}"><span
                                class="text font-weight-normal"><i class="fas fa-sign-in-alt"></i></span><span class="ml-2">Login</span></a>
                    </div>
                    {# end of login button #}
                {% endif %}


            </div>

    </div>

</nav>


<div class="container">
    {% block content %}{% endblock %}
</div>

{% block js_scripts %}{% endblock %}

</body>
</html>

app/reports/templates/reports/edit_service_members_chain.html
{% extends 'reports/base.html' %}

{#loads custom tags#}

{% block extra_head %}
    {#    custom jquery blib: SELECT2    #}
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/css/select2.min.css" rel="stylesheet"/>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/js/select2.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/i18n/ru.js"></script>
{% endblock %}


{% block content %}
    <p><h3 class="text-white">Всі посередники:</h3></p>
    <hr>


    <form method="POST">{% csrf_token %}

        {% for servicemember in serviceman_chain %}

            <div class="row left-bordered-row ml-0 bg-light">

                {# editing chain member#}
                {% if swap_id == servicemember.id %}
                    <div class="col-12 d-flex align-items-center">
                        <select name="swap_id"></select>
                        <button type="submit" class="btn btn-secondary btn-sm mx-3" name="submit_new_id"
                                value="{{ servicemember.id }}">
                            замінити<i class="fas fa-exchange-alt m-1"></i>
                        </button>
                        {#submit chain member id editing button#}
                    </div>
                    {# end of editing chain member #}

                {# member representation block #}
                {% else %}
                    <div class="col-11">
                        {{ servicemember.rank.name }} {{ servicemember }}
                        <br>{{ servicemember.position }}
                    </div>
                    {# end of member representation block #}

                    {# edit buttons group#}
                    <div class="col-1 d-flex justify-content-end align-items-center pr-0">
                        {% if not forloop.first %}
                            <div data-toggle="tooltip" data-placement="top" title="редагувати">
                                <button type="submit" class="btn btn-light btn-sm text-info mr-1"
                                        name="edit_chain_id"
                                        value="{{ servicemember.id }}"><span class="fas fa-edit fa-1x"></span>
                                </button>
                            </div>
                        {% endif %}

                        {% if not forloop.first and not forloop.last %}
                            <div data-toggle="tooltip" data-placement="top" title="видалити">
                                <button type="submit" class="btn btn-light btn-sm text-danger mr-1"
                                        name="remove_chain_id"
                                        value="{{ servicemember.id }}"
                                        onclick="return window.confirm('Видалити запис: {{ servicemember.rank.name }} {{ servicemember }}?')">
                                    <span class="far fa-trash-alt fa-1x"></span>
                                </button>
                            </div>
                        {% endif %}
                    </div>
                    {# end of edit buttons group#}
                {% endif %}
            </div>

            {# adding arrow after each line#}
            {% if not forloop.last %}

                <i class="ml-0 fas fa-arrow-down fa-1x text-white"></i>
            {% endif %}
        {% endfor %}

        {% if swap_id is None %}
            <button class="btn btn-bordered-primary bg-secondary float-right text-light mt-3"
                    type="submit" name="submit_chain_editing">
                <span>Далі</span><i class="fas fa-angle-double-right ml-2"></i>
            </button>
        {% endif %}

    </form>


{% endblock %}











{#block submitting form by pressing Enter button#}
{% block js_scripts %}
    <script>
        //init jquery tooltip for hover popup
        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })

        $(document).ready(function () {

            // Initialize select2
            var csrf_token = '{{ csrf_token }}';
            $('select').select2({
                placeholder: "пошук (звання, ім'я, прізвище)",
                allowClear: true,
                language: "ru",
                delay: 250,
                width: '400px',

                ajax: {
                    csrfmiddlewaretoken: csrf_token,
                    url: '/search_member/',
                    method: 'POST',
                    dataType: 'json',
                    // Additional AJAX parameters go here
                    data: function (params) {
                        var query = {
                            csrfmiddlewaretoken: csrf_token,
                            filter_param: params.term,
                            name_format: $(this).attr('title')
                        }
                        return query;
                    },
                    processResults: function (data) {
                        // Transforms the top-level key of the response object from 'items' to 'results'
                        //console.log("success")
                        console.log(data)
                        return {
                            results: data
                        };
                    }
                }
            });

            $('select').select2('open');

        });

    </script>
{% endblock %}

app/reports/templates/reports/index.html
{% extends 'reports/base.html' %}

{% load static %}

{% block extra_head %}
    <link rel="stylesheet" type="text/css" href="{% static 'custom-css/backgroud_styles.css' %}"/>
{% endblock %}

{% block content %}
            <div class="w-90 mx-auto" style="margin-top: 200px">
                <div class="row">
                    <div class="col text-center">
                        <i class="fab fa-docker text-warning fa-9x"></i>
                        <i class="fas fa-file-alt fa-1x text-info"></i>
                        <i class="fas fa-file-alt fa-2x text-danger"></i>
                        <i class="fas fa-file-alt fa-3x text-danger"></i>
                        <i class="fas fa-file-alt fa-4x text-danger"></i>
                        <i class="fas fa-file-alt fa-5x text-info"></i>
                        <i class="fas fa-file-alt fa-6x text-danger"></i>
                        <i class="fas fa-file-alt fa-7x text-danger"></i>
                        <i class="fas fa-file-alt fa-8x text-danger"></i>
                        <i class="fas fa-file-alt fa-9x text-info"></i>
                    </div>
                </div>
            </div>

{% endblock %}

app/reports/templates/reports/reports_list.html
{% extends 'reports/base.html' %}
{#{% load static %}#}


{% block content %}
    <div class="alert alert-info align-items-center my-0 py-0 pr-2" role="alert">
        <div class="form-group row my-1">
            <div class="col-12 d-flex">
                <h4 class="mr-auto mt-1"><i class="fas fa-server mr-2"></i>Оберіть рапорт:</h4>
                <form id='search' class="d-flex w-50" method='POST' action='{% url 'reports:reports_list' %}'>
                    {% csrf_token %}
                    <input type="search" class="form-control mr-2" placeholder="Пошук" id="filter_param"
                           name="filter_param">
                    <button type="submit" class="btn btn-outline-info">Шукати</button>
                </form>
            </div>
        </div>
    </div>


    {#    search results message#}
    {% if filter_param %}
        {% if page_obj.paginator.count > 0 %}
            <div class="alert alert-success d-flex align-items-center mb-1 py-1" role="alert">
                по запиту: <span class="badge badge-secondary mx-2 p-1">{{ filter_param }}</span>
                знайдено: {{ page_obj.paginator.count }}
                <a href="{% url 'reports:reports_list' %}"
                   class="btn ml-auto px-3 py-2"><i class="fas fa-times text-secondary"></i></a>
            </div>
        {% else %}
            <div class="alert alert-danger d-flex align-items-center mb-1 py-1" role="alert">
                по запиту: <span class="badge badge-secondary mx-2 p-1">{{ filter_param }}</span> нiчого не знайдено
                <a href="{% url 'reports:reports_list' %}"
                   class="btn ml-auto px-3 py-2"><i class="fas fa-times text-secondary"></i></a>
            </div>
        {% endif %}
    {% endif %}
    <hr class="my-2">
    {# end of search results message#}


    {# reports list accordion #}
    {% for report in page_obj %}
        <div class="accordion mb-0" id="accordion-1">

            <div class="card border-info my-2">
                <div class="card-header" id="heading-{{ forloop.counter0 }}">
                    <h2 class="mb-0">
                        <button class="btn btn-link text-dark" type="button" data-toggle="collapse"
                                data-target="#collapse-{{ forloop.counter0 }}"
                                aria-expanded="false" aria-controls="collapseOne">
                            <h6>{{ report.title|upper }}</h6>
                        </button>
                    </h2>
                </div>

                <div id="collapse-{{ forloop.counter0 }}" class="collapse collapsed"
                     aria-labelledby="#heading-{{ forloop.counter0 }}"
                     data-parent="#accordion-1">
                    <div class="card-body">
                        {#                        <p><u>Зразок рапорту:</u></p>#}
                        {{ report.body_sample }}
                        <a class="btn btn-bordered-primary text-light bg-secondary float-right my-3"
                           href="{% url 'reports:proceed_chosen_report' report_id=report.id %}">
                            Далі <i class="fas fa-angle-double-right ml-1"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    {#    end of reports list accordion#}


    {#  page navigation  #}
    <nav aria-label="PAGES NAVIGATION">
        {% if page_obj.has_other_pages %}
            <ul class="pagination justify-content-center">
                {# prev, first page #}
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link text-info"
                                             href="?{% if filter_param %}filter_param={{ filter_param }}&{% endif %}page={{ page_obj.previous_page_number }}">Взад</a>
                    </li>
                    <li class="page-item"><a class="page-link text-info"
                                             href="?{% if filter_param %}filter_param={{ filter_param }}&{% endif %}page=1">&laquo;&laquo;</a>
                    </li>
                {% else %}
                    <li class="page-item disabled"><a class="page-link" href="#">Взад</a></li>
                    <li class="page-item disabled"><a class="page-link" href="#">&laquo;&laquo;</a></li>
                {% endif %}
                {# end of prev, first page #}

                {# main pagination #}
                {% for i in page_obj.paginator.page_range %}
                    {% if i == page_obj.number %}
                        <li class="page-item active">
                            <span class="page-link text-dark bg-info">{{ page_obj.number }}</span>
                            <span class="sr-only">(current)</span></span>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link text-info"
                               href="?{% if filter_param %}filter_param={{ filter_param }}&{% endif %}page={{ i }}">{{ i }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
                {# end of main pagination #}


                {# next, last page #}
                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link text-info"
                                             href="?{% if filter_param %}filter_param={{ filter_param }}&{% endif %}page={{ page_obj.paginator.num_pages }}">&raquo;&raquo;</a>
                    </li>
                    <li class="page-item"><a class="page-link text-info"
                                             href="?{% if filter_param %}filter_param={{ filter_param }}&{% endif %}page={{ page_obj.next_page_number }}">Вперед</a>
                    </li>
                {% else %}
                    <li class="page-item disabled"><a class="page-link" href="#">&raquo;&raquo;</a></li>
                    <li class="page-item disabled"><a class="page-link" href="#">Вперед</a></li>
                {% endif %}
                {# end of next, last page #}

            </ul>
        {% endif %}
    </nav>
    {# end of page navigation #}

{% endblock %}